name: deploy-to-firebase
run-name: ${{ github.actor }} is deploying ${{ github.event.repository.name }} to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸŸ¢ Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: ðŸ“¥ Cloning repo
        uses: actions/checkout@v3
      - name: ðŸ“¦ Install packages
        run: npm i --force
      - name: ðŸ”¨ Building
        run: npm run build
      - name: ðŸš€ Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
